import fs from 'fs'
import ts from 'typescript'
import * as prettier from 'prettier'

// The maximum number of arguments to generate overloads for.
const MAX_ARGUMENTS = 20

/**
 * Simply passes the value {@link x} to the function {@param fn} and returns the
 * result. In other words, creates a local binding (variable) for the value.
 * Equivalent to a `let` form in Lisp.
 *
 * @template T, R
 * @param {T} x The value
 * @param {(x: T) => R} fn A function which uses the value.
 * @returns {R} The result of applying the function to the value.
 */
const withBinding = (x, fn) => fn(x)

const anyMiddlewareType = ts.factory.createTypeReferenceNode('Middleware', [
  ts.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
  ts.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
  ts.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
])

const declarations = [
  /* typescript */ `
    /*
     * DO NOT EDIT THIS FILE
     *
     * This file contains overloads for the arities of the \`composeMiddleware\`
     * function. To change it, edit \`scripts/generateComposeMiddleware.js\` and run
     * \`npm run generate-compose\` (or \`npm run generate-compose:watch\`).
     * 
     * This file is committed to the repository, as it should rarely change.
     */

    import {
      AddedContextOf,
      EnvOf,
      Middleware,
      RequiredContextOf,
    } from './bindings'

    /**
     * Returns the result of satisfying the {@link Requirements} with the
     * {@link With}. If a key in the {@link Requirements} is BOOKMARK
     */
    export type Satisfy<Requirements, With> =
      With extends Pick<Requirements, keyof Requirements & keyof With>
        ? Omit<Requirements, keyof With>
        : never
  `,

  /* typescript */ `
    /**
     * Composes multiple middleware functions into a single middleware function. The
     * request will be seen by the composed middleware in the order they are given.
     *
     * Note: Due to TypeScript limitations, each arity of this function must be a
     * separate overload. To compose more than ${MAX_ARGUMENTS} middleware functions, simply nest
     * smaller compositions.
     */
  `,

  ...Array.from({ length: MAX_ARGUMENTS })
    .map((_, i) => i + 1)
    .map((n) => createComposeMiddlewareOverloadDeclaration(n)),

  /* typescript */ `
    export { composeMiddleware };
  `,
]

/**
 * Creates a TypeScript function declaration for the `composeMiddleware`
 * function with the given number of middleware arguments.
 *
 * @param {number} argCount The number of middleware arguments.
 * @returns {ts.FunctionDeclaration} The TypeScript function declaration.
 */
function createComposeMiddlewareOverloadDeclaration(argCount) {
  const ns = Array.from({ length: argCount }).map((_, i) => i + 1)

  return ts.factory.createFunctionDeclaration(
    [ts.factory.createToken(ts.SyntaxKind.DeclareKeyword)],
    undefined,
    'composeMiddleware',
    [
      ...ns.flatMap((n) => {
        return [
          ts.factory.createTypeParameterDeclaration(
            undefined,
            `M${n}`,
            anyMiddlewareType
          ),
          ts.factory.createTypeParameterDeclaration(
            undefined,
            `M${n}R`,
            withBinding(
              ts.factory.createTypeReferenceNode('RequiredContextOf', [
                ts.factory.createTypeReferenceNode(`M${n}`),
              ]),
              (requiredContext) =>
                n === 1
                  ? requiredContext
                  : ts.factory.createTypeReferenceNode('Satisfy', [
                      requiredContext,
                      ts.factory.createTypeReferenceNode(`M${n - 1}C`),
                    ])
            )
          ),
          ts.factory.createTypeParameterDeclaration(
            undefined,
            `M${n}C`,
            ts.factory.createIntersectionTypeNode([
              ts.factory.createTypeReferenceNode('AddedContextOf', [
                ts.factory.createTypeReferenceNode(`M${n}`),
              ]),
              ...(n === 1
                ? []
                : [ts.factory.createTypeReferenceNode(`M${n - 1}C`)]),
            ])
          ),
        ]
      }),
    ],
    ns.map((n) =>
      ts.factory.createParameterDeclaration(
        undefined,
        undefined,
        `m${n}`,
        undefined,
        ts.factory.createTypeReferenceNode(`M${n}`),
        undefined
      )
    ),
    ts.factory.createTypeReferenceNode('Middleware', [
      ts.factory.createIntersectionTypeNode(
        ns.map((n) =>
          withBinding(
            ts.factory.createTypeReferenceNode('RequiredContextOf', [
              ts.factory.createTypeReferenceNode(`M${n}`),
            ]),
            (requiredContext) =>
              n === 1
                ? requiredContext
                : ts.factory.createTypeReferenceNode('Satisfy', [
                    requiredContext,
                    ts.factory.createTypeReferenceNode(`M${n - 1}C`),
                  ])
          )
        )
      ),
      ts.factory.createTypeReferenceNode(`M${ns[ns.length - 1]}C`),
      ts.factory.createIntersectionTypeNode(
        ns.map((n) =>
          ts.factory.createTypeReferenceNode('EnvOf', [
            ts.factory.createTypeReferenceNode(`M${n}`),
          ])
        )
      ),
    ]),
    undefined
  )
}

// Output

const filepath = 'src/composeMiddleware.d.ts'

const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed })
const resultFile = ts.createSourceFile(
  filepath,
  '',
  ts.ScriptTarget.Latest,
  false,
  ts.ScriptKind.TSX
)

const output = declarations
  .map((node) =>
    typeof node === 'string'
      ? node
      : printer.printNode(ts.EmitHint.Unspecified, node, resultFile)
  )
  .join('\n\n')

const prettierConfig = await prettier.resolveConfig(filepath)
const formattedOutput = await prettier.format(output, {
  filepath,
  ...prettierConfig,
})
fs.writeFileSync(filepath, formattedOutput)
