import fs from 'fs'
import ts from 'typescript'
import * as prettier from 'prettier'

// The maximum number of arguments to generate overloads for.
const MAX_ARGUMENTS = 20

/**
 * Simply passes the value {@link x} to the function {@param fn} and returns the
 * result. In other words, creates a local binding (variable) for the value.
 * Equivalent to a `let` form in Lisp.
 *
 * @template T, R
 * @param {T} x The value
 * @param {(x: T) => R} fn A function which uses the value.
 * @returns {R} The result of applying the function to the value.
 */
const withBinding = (x, fn) => fn(x)

const anyMiddlewareType = ts.factory.createTypeReferenceNode('Middleware', [
  ts.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
  ts.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
  ts.factory.createKeywordTypeNode(ts.SyntaxKind.AnyKeyword),
])

const declarations = [
  /* typescript */ `
    /*
     * DO NOT EDIT THIS FILE
     *
     * This file contains overloads for the arities of the \`composeMiddleware\`
     * function. To change it, edit \`scripts/generateComposeMiddleware.js\` and run
     * \`npm run generate-compose\` (or \`npm run generate-compose:watch\`).
     * 
     * This file is committed to the repository, as it should rarely change.
     */

    /**
     * A Handler handles a request. It's an async function which takes a
     * {@link Request} and returns a {@link Response}. It also has access to the
     * context and environment for the request.
     *
     * @template Context The context keys used by the handler.
     * @template Env The environment keys used by the handler.
     */
    type Handler<Context extends {}, Env extends {} = {}> = (
      request: Request,
      env: Env,
      ctx: Context,
    ) => Promise<Response>;

    /**
     * A Middleware is a function that takes a {@link Handler} and returns a new
     * one. It has access to the context and environment for the request. It can
     * add to the context, or modify it, but it should not remove keys, so that
     * upstream middleware can pass context to downstream middleware. It should
     * generally not modify the environment, as that is shared across all requests.
     *
     * @template RequiredContext The context required by the middleware. These keys
     * must be either provided by upstream middleware, or given to the ultimate
     * handler.
     * @template AddedContext The context added by the middleware. These keys will
     * be available to downstream middleware.
     * @template Env The environment keys used by the middleware. The entire
     * environment should be passed to the outermost handler, at the top of the
     * middleware stack. Middleware shouldn't modify the environment, and should
     * pass it in its entirety when it calls the next handler.
     */
    type Middleware<
      RequiredContext extends {},
      AddedContext extends {} = {},
      Env extends {} = {},
    > = <HandlerRequiredContext, HandlerEnv>(
      h: Handler<AddedContext & HandlerRequiredContext, Env & HandlerEnv>,
    ) => Handler<RequiredContext & HandlerRequiredContext, Env & HandlerEnv>;
    
    export type RequiredContextOf<M extends Middleware<any, any, any>> =
      M extends Middleware<infer T, any, any> ? T : never;

    export type AddedContextOf<M extends Middleware<any, any, any>> =
      M extends Middleware<any, infer T, any> ? T : never;
    
    export type EnvOf<M extends Middleware<any, any, any>> =
      M extends Middleware<any, any, infer T> ? T : never;

    /**
     * Returns the result of satisfying the {@link Requirements} with the
     * {@link With}. If a key in the {@link Requirements} is BOOKMARK
     */
    export type Satisfy<Requirements, With> =
      With extends Pick<Requirements, keyof Requirements & keyof With>
        ? Omit<Requirements, keyof With>
        : never;
  `,

  ...Array.from({ length: MAX_ARGUMENTS })
    .map((_, i) => i + 1)
    .map((n) => createComposeMiddlewareOverloadDeclaration(n)),

  /* typescript */ `
    function composeMiddleware(
      ...middlewares: Middleware<any, any, any>[]
    ): Middleware<any, any, any> {
      return (handler) => middlewares.reduceRight((h, m) => m(h), handler);
    }
  
    export { composeMiddleware, Middleware, Handler };
  `,
]

/**
 * Creates a TypeScript function declaration for the `composeMiddleware`
 * function with the given number of middleware arguments.
 *
 * @param {number} argCount The number of middleware arguments.
 * @returns {ts.FunctionDeclaration} The TypeScript function declaration.
 */
function createComposeMiddlewareOverloadDeclaration(argCount) {
  const ns = Array.from({ length: argCount }).map((_, i) => i + 1)

  return ts.factory.createFunctionDeclaration(
    undefined,
    undefined,
    'composeMiddleware',
    [
      ...ns.flatMap((n) => {
        return [
          ts.factory.createTypeParameterDeclaration(
            undefined,
            `M${n}`,
            anyMiddlewareType
          ),
          ts.factory.createTypeParameterDeclaration(
            undefined,
            `M${n}R`,
            withBinding(
              ts.factory.createTypeReferenceNode('RequiredContextOf', [
                ts.factory.createTypeReferenceNode(`M${n}`),
              ]),
              (requiredContext) =>
                n === 1
                  ? requiredContext
                  : ts.factory.createTypeReferenceNode('Satisfy', [
                      requiredContext,
                      ts.factory.createTypeReferenceNode(`M${n - 1}C`),
                    ])
            )
          ),
          ts.factory.createTypeParameterDeclaration(
            undefined,
            `M${n}C`,
            ts.factory.createIntersectionTypeNode([
              ts.factory.createTypeReferenceNode('AddedContextOf', [
                ts.factory.createTypeReferenceNode(`M${n}`),
              ]),
              ...(n === 1
                ? []
                : [ts.factory.createTypeReferenceNode(`M${n - 1}C`)]),
            ])
          ),
        ]
      }),
    ],
    ns.map((n) =>
      ts.factory.createParameterDeclaration(
        undefined,
        undefined,
        `m${n}`,
        undefined,
        ts.factory.createTypeReferenceNode(`M${n}`),
        undefined
      )
    ),
    ts.factory.createTypeReferenceNode('Middleware', [
      ts.factory.createIntersectionTypeNode(
        ns.map((n) =>
          withBinding(
            ts.factory.createTypeReferenceNode('RequiredContextOf', [
              ts.factory.createTypeReferenceNode(`M${n}`),
            ]),
            (requiredContext) =>
              n === 1
                ? requiredContext
                : ts.factory.createTypeReferenceNode('Satisfy', [
                    requiredContext,
                    ts.factory.createTypeReferenceNode(`M${n - 1}C`),
                  ])
          )
        )
      ),
      ts.factory.createTypeReferenceNode(`M${ns[ns.length - 1]}C`),
      ts.factory.createIntersectionTypeNode(
        ns.map((n) =>
          ts.factory.createTypeReferenceNode('EnvOf', [
            ts.factory.createTypeReferenceNode(`M${n}`),
          ])
        )
      ),
    ]),
    undefined
  )
}

// Output

const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed })
const resultFile = ts.createSourceFile(
  'noodle4-output.ts',
  '',
  ts.ScriptTarget.Latest,
  false,
  ts.ScriptKind.TSX
)

const output = declarations
  .map((node) =>
    typeof node === 'string'
      ? node
      : printer.printNode(ts.EmitHint.Unspecified, node, resultFile)
  )
  .join('\n\n')

const filepath = 'src/composeMiddleware.ts'
const prettierConfig = await prettier.resolveConfig(filepath)
const formattedOutput = await prettier.format(output, {
  filepath,
  ...prettierConfig,
})
fs.writeFileSync(filepath, formattedOutput)
