/*
 * DO NOT EDIT THIS FILE
 *
 * This file contains overloads for the arities of the `composeMiddleware`
 * function. To change it, edit `scripts/generateComposeMiddleware.js` and run
 * `npm run generate-compose` (or `npm run generate-compose:watch`).
 *
 * This file is committed to the repository, as it should rarely change.
 */

import {
  AddedContextOf,
  EnvOf,
  Middleware,
  RequiredContextOf,
} from './bindings'

/**
 * Returns the result of satisfying the {@link Requirements} with the
 * {@link With}. If a key in the {@link Requirements} is BOOKMARK
 */
export type Satisfy<Requirements, With> =
  With extends Pick<Requirements, keyof Requirements & keyof With>
    ? Omit<Requirements, keyof With>
    : never

/**
 * Composes multiple middleware functions into a single middleware function. The
 * request will be seen by the composed middleware in the order they are given.
 *
 * Note: Due to TypeScript limitations, each arity of this function must be a
 * separate overload. To compose more than 20 middleware functions, simply nest
 * smaller compositions.
 */

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
>(m1: M1): Middleware<RequiredContextOf<M1>, M1C, EnvOf<M1>>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
>(
  m1: M1,
  m2: M2
): Middleware<
  RequiredContextOf<M1> & Satisfy<RequiredContextOf<M2>, M1C>,
  M2C,
  EnvOf<M1> & EnvOf<M2>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
>(
  m1: M1,
  m2: M2,
  m3: M3
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C>,
  M3C,
  EnvOf<M1> & EnvOf<M2> & EnvOf<M3>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C>,
  M4C,
  EnvOf<M1> & EnvOf<M2> & EnvOf<M3> & EnvOf<M4>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C>,
  M5C,
  EnvOf<M1> & EnvOf<M2> & EnvOf<M3> & EnvOf<M4> & EnvOf<M5>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C>,
  M6C,
  EnvOf<M1> & EnvOf<M2> & EnvOf<M3> & EnvOf<M4> & EnvOf<M5> & EnvOf<M6>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C>,
  M7C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C>,
  M8C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C>,
  M9C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C>,
  M10C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C>,
  M11C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
  M12 extends Middleware<any, any, any>,
  M12R extends Satisfy<RequiredContextOf<M12>, M11C>,
  M12C extends AddedContextOf<M12> & M11C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11,
  m12: M12
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C> &
    Satisfy<RequiredContextOf<M12>, M11C>,
  M12C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11> &
    EnvOf<M12>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
  M12 extends Middleware<any, any, any>,
  M12R extends Satisfy<RequiredContextOf<M12>, M11C>,
  M12C extends AddedContextOf<M12> & M11C,
  M13 extends Middleware<any, any, any>,
  M13R extends Satisfy<RequiredContextOf<M13>, M12C>,
  M13C extends AddedContextOf<M13> & M12C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11,
  m12: M12,
  m13: M13
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C> &
    Satisfy<RequiredContextOf<M12>, M11C> &
    Satisfy<RequiredContextOf<M13>, M12C>,
  M13C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11> &
    EnvOf<M12> &
    EnvOf<M13>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
  M12 extends Middleware<any, any, any>,
  M12R extends Satisfy<RequiredContextOf<M12>, M11C>,
  M12C extends AddedContextOf<M12> & M11C,
  M13 extends Middleware<any, any, any>,
  M13R extends Satisfy<RequiredContextOf<M13>, M12C>,
  M13C extends AddedContextOf<M13> & M12C,
  M14 extends Middleware<any, any, any>,
  M14R extends Satisfy<RequiredContextOf<M14>, M13C>,
  M14C extends AddedContextOf<M14> & M13C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11,
  m12: M12,
  m13: M13,
  m14: M14
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C> &
    Satisfy<RequiredContextOf<M12>, M11C> &
    Satisfy<RequiredContextOf<M13>, M12C> &
    Satisfy<RequiredContextOf<M14>, M13C>,
  M14C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11> &
    EnvOf<M12> &
    EnvOf<M13> &
    EnvOf<M14>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
  M12 extends Middleware<any, any, any>,
  M12R extends Satisfy<RequiredContextOf<M12>, M11C>,
  M12C extends AddedContextOf<M12> & M11C,
  M13 extends Middleware<any, any, any>,
  M13R extends Satisfy<RequiredContextOf<M13>, M12C>,
  M13C extends AddedContextOf<M13> & M12C,
  M14 extends Middleware<any, any, any>,
  M14R extends Satisfy<RequiredContextOf<M14>, M13C>,
  M14C extends AddedContextOf<M14> & M13C,
  M15 extends Middleware<any, any, any>,
  M15R extends Satisfy<RequiredContextOf<M15>, M14C>,
  M15C extends AddedContextOf<M15> & M14C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11,
  m12: M12,
  m13: M13,
  m14: M14,
  m15: M15
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C> &
    Satisfy<RequiredContextOf<M12>, M11C> &
    Satisfy<RequiredContextOf<M13>, M12C> &
    Satisfy<RequiredContextOf<M14>, M13C> &
    Satisfy<RequiredContextOf<M15>, M14C>,
  M15C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11> &
    EnvOf<M12> &
    EnvOf<M13> &
    EnvOf<M14> &
    EnvOf<M15>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
  M12 extends Middleware<any, any, any>,
  M12R extends Satisfy<RequiredContextOf<M12>, M11C>,
  M12C extends AddedContextOf<M12> & M11C,
  M13 extends Middleware<any, any, any>,
  M13R extends Satisfy<RequiredContextOf<M13>, M12C>,
  M13C extends AddedContextOf<M13> & M12C,
  M14 extends Middleware<any, any, any>,
  M14R extends Satisfy<RequiredContextOf<M14>, M13C>,
  M14C extends AddedContextOf<M14> & M13C,
  M15 extends Middleware<any, any, any>,
  M15R extends Satisfy<RequiredContextOf<M15>, M14C>,
  M15C extends AddedContextOf<M15> & M14C,
  M16 extends Middleware<any, any, any>,
  M16R extends Satisfy<RequiredContextOf<M16>, M15C>,
  M16C extends AddedContextOf<M16> & M15C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11,
  m12: M12,
  m13: M13,
  m14: M14,
  m15: M15,
  m16: M16
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C> &
    Satisfy<RequiredContextOf<M12>, M11C> &
    Satisfy<RequiredContextOf<M13>, M12C> &
    Satisfy<RequiredContextOf<M14>, M13C> &
    Satisfy<RequiredContextOf<M15>, M14C> &
    Satisfy<RequiredContextOf<M16>, M15C>,
  M16C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11> &
    EnvOf<M12> &
    EnvOf<M13> &
    EnvOf<M14> &
    EnvOf<M15> &
    EnvOf<M16>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
  M12 extends Middleware<any, any, any>,
  M12R extends Satisfy<RequiredContextOf<M12>, M11C>,
  M12C extends AddedContextOf<M12> & M11C,
  M13 extends Middleware<any, any, any>,
  M13R extends Satisfy<RequiredContextOf<M13>, M12C>,
  M13C extends AddedContextOf<M13> & M12C,
  M14 extends Middleware<any, any, any>,
  M14R extends Satisfy<RequiredContextOf<M14>, M13C>,
  M14C extends AddedContextOf<M14> & M13C,
  M15 extends Middleware<any, any, any>,
  M15R extends Satisfy<RequiredContextOf<M15>, M14C>,
  M15C extends AddedContextOf<M15> & M14C,
  M16 extends Middleware<any, any, any>,
  M16R extends Satisfy<RequiredContextOf<M16>, M15C>,
  M16C extends AddedContextOf<M16> & M15C,
  M17 extends Middleware<any, any, any>,
  M17R extends Satisfy<RequiredContextOf<M17>, M16C>,
  M17C extends AddedContextOf<M17> & M16C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11,
  m12: M12,
  m13: M13,
  m14: M14,
  m15: M15,
  m16: M16,
  m17: M17
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C> &
    Satisfy<RequiredContextOf<M12>, M11C> &
    Satisfy<RequiredContextOf<M13>, M12C> &
    Satisfy<RequiredContextOf<M14>, M13C> &
    Satisfy<RequiredContextOf<M15>, M14C> &
    Satisfy<RequiredContextOf<M16>, M15C> &
    Satisfy<RequiredContextOf<M17>, M16C>,
  M17C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11> &
    EnvOf<M12> &
    EnvOf<M13> &
    EnvOf<M14> &
    EnvOf<M15> &
    EnvOf<M16> &
    EnvOf<M17>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
  M12 extends Middleware<any, any, any>,
  M12R extends Satisfy<RequiredContextOf<M12>, M11C>,
  M12C extends AddedContextOf<M12> & M11C,
  M13 extends Middleware<any, any, any>,
  M13R extends Satisfy<RequiredContextOf<M13>, M12C>,
  M13C extends AddedContextOf<M13> & M12C,
  M14 extends Middleware<any, any, any>,
  M14R extends Satisfy<RequiredContextOf<M14>, M13C>,
  M14C extends AddedContextOf<M14> & M13C,
  M15 extends Middleware<any, any, any>,
  M15R extends Satisfy<RequiredContextOf<M15>, M14C>,
  M15C extends AddedContextOf<M15> & M14C,
  M16 extends Middleware<any, any, any>,
  M16R extends Satisfy<RequiredContextOf<M16>, M15C>,
  M16C extends AddedContextOf<M16> & M15C,
  M17 extends Middleware<any, any, any>,
  M17R extends Satisfy<RequiredContextOf<M17>, M16C>,
  M17C extends AddedContextOf<M17> & M16C,
  M18 extends Middleware<any, any, any>,
  M18R extends Satisfy<RequiredContextOf<M18>, M17C>,
  M18C extends AddedContextOf<M18> & M17C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11,
  m12: M12,
  m13: M13,
  m14: M14,
  m15: M15,
  m16: M16,
  m17: M17,
  m18: M18
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C> &
    Satisfy<RequiredContextOf<M12>, M11C> &
    Satisfy<RequiredContextOf<M13>, M12C> &
    Satisfy<RequiredContextOf<M14>, M13C> &
    Satisfy<RequiredContextOf<M15>, M14C> &
    Satisfy<RequiredContextOf<M16>, M15C> &
    Satisfy<RequiredContextOf<M17>, M16C> &
    Satisfy<RequiredContextOf<M18>, M17C>,
  M18C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11> &
    EnvOf<M12> &
    EnvOf<M13> &
    EnvOf<M14> &
    EnvOf<M15> &
    EnvOf<M16> &
    EnvOf<M17> &
    EnvOf<M18>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
  M12 extends Middleware<any, any, any>,
  M12R extends Satisfy<RequiredContextOf<M12>, M11C>,
  M12C extends AddedContextOf<M12> & M11C,
  M13 extends Middleware<any, any, any>,
  M13R extends Satisfy<RequiredContextOf<M13>, M12C>,
  M13C extends AddedContextOf<M13> & M12C,
  M14 extends Middleware<any, any, any>,
  M14R extends Satisfy<RequiredContextOf<M14>, M13C>,
  M14C extends AddedContextOf<M14> & M13C,
  M15 extends Middleware<any, any, any>,
  M15R extends Satisfy<RequiredContextOf<M15>, M14C>,
  M15C extends AddedContextOf<M15> & M14C,
  M16 extends Middleware<any, any, any>,
  M16R extends Satisfy<RequiredContextOf<M16>, M15C>,
  M16C extends AddedContextOf<M16> & M15C,
  M17 extends Middleware<any, any, any>,
  M17R extends Satisfy<RequiredContextOf<M17>, M16C>,
  M17C extends AddedContextOf<M17> & M16C,
  M18 extends Middleware<any, any, any>,
  M18R extends Satisfy<RequiredContextOf<M18>, M17C>,
  M18C extends AddedContextOf<M18> & M17C,
  M19 extends Middleware<any, any, any>,
  M19R extends Satisfy<RequiredContextOf<M19>, M18C>,
  M19C extends AddedContextOf<M19> & M18C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11,
  m12: M12,
  m13: M13,
  m14: M14,
  m15: M15,
  m16: M16,
  m17: M17,
  m18: M18,
  m19: M19
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C> &
    Satisfy<RequiredContextOf<M12>, M11C> &
    Satisfy<RequiredContextOf<M13>, M12C> &
    Satisfy<RequiredContextOf<M14>, M13C> &
    Satisfy<RequiredContextOf<M15>, M14C> &
    Satisfy<RequiredContextOf<M16>, M15C> &
    Satisfy<RequiredContextOf<M17>, M16C> &
    Satisfy<RequiredContextOf<M18>, M17C> &
    Satisfy<RequiredContextOf<M19>, M18C>,
  M19C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11> &
    EnvOf<M12> &
    EnvOf<M13> &
    EnvOf<M14> &
    EnvOf<M15> &
    EnvOf<M16> &
    EnvOf<M17> &
    EnvOf<M18> &
    EnvOf<M19>
>

declare function composeMiddleware<
  M1 extends Middleware<any, any, any>,
  M1R extends RequiredContextOf<M1>,
  M1C extends AddedContextOf<M1>,
  M2 extends Middleware<any, any, any>,
  M2R extends Satisfy<RequiredContextOf<M2>, M1C>,
  M2C extends AddedContextOf<M2> & M1C,
  M3 extends Middleware<any, any, any>,
  M3R extends Satisfy<RequiredContextOf<M3>, M2C>,
  M3C extends AddedContextOf<M3> & M2C,
  M4 extends Middleware<any, any, any>,
  M4R extends Satisfy<RequiredContextOf<M4>, M3C>,
  M4C extends AddedContextOf<M4> & M3C,
  M5 extends Middleware<any, any, any>,
  M5R extends Satisfy<RequiredContextOf<M5>, M4C>,
  M5C extends AddedContextOf<M5> & M4C,
  M6 extends Middleware<any, any, any>,
  M6R extends Satisfy<RequiredContextOf<M6>, M5C>,
  M6C extends AddedContextOf<M6> & M5C,
  M7 extends Middleware<any, any, any>,
  M7R extends Satisfy<RequiredContextOf<M7>, M6C>,
  M7C extends AddedContextOf<M7> & M6C,
  M8 extends Middleware<any, any, any>,
  M8R extends Satisfy<RequiredContextOf<M8>, M7C>,
  M8C extends AddedContextOf<M8> & M7C,
  M9 extends Middleware<any, any, any>,
  M9R extends Satisfy<RequiredContextOf<M9>, M8C>,
  M9C extends AddedContextOf<M9> & M8C,
  M10 extends Middleware<any, any, any>,
  M10R extends Satisfy<RequiredContextOf<M10>, M9C>,
  M10C extends AddedContextOf<M10> & M9C,
  M11 extends Middleware<any, any, any>,
  M11R extends Satisfy<RequiredContextOf<M11>, M10C>,
  M11C extends AddedContextOf<M11> & M10C,
  M12 extends Middleware<any, any, any>,
  M12R extends Satisfy<RequiredContextOf<M12>, M11C>,
  M12C extends AddedContextOf<M12> & M11C,
  M13 extends Middleware<any, any, any>,
  M13R extends Satisfy<RequiredContextOf<M13>, M12C>,
  M13C extends AddedContextOf<M13> & M12C,
  M14 extends Middleware<any, any, any>,
  M14R extends Satisfy<RequiredContextOf<M14>, M13C>,
  M14C extends AddedContextOf<M14> & M13C,
  M15 extends Middleware<any, any, any>,
  M15R extends Satisfy<RequiredContextOf<M15>, M14C>,
  M15C extends AddedContextOf<M15> & M14C,
  M16 extends Middleware<any, any, any>,
  M16R extends Satisfy<RequiredContextOf<M16>, M15C>,
  M16C extends AddedContextOf<M16> & M15C,
  M17 extends Middleware<any, any, any>,
  M17R extends Satisfy<RequiredContextOf<M17>, M16C>,
  M17C extends AddedContextOf<M17> & M16C,
  M18 extends Middleware<any, any, any>,
  M18R extends Satisfy<RequiredContextOf<M18>, M17C>,
  M18C extends AddedContextOf<M18> & M17C,
  M19 extends Middleware<any, any, any>,
  M19R extends Satisfy<RequiredContextOf<M19>, M18C>,
  M19C extends AddedContextOf<M19> & M18C,
  M20 extends Middleware<any, any, any>,
  M20R extends Satisfy<RequiredContextOf<M20>, M19C>,
  M20C extends AddedContextOf<M20> & M19C,
>(
  m1: M1,
  m2: M2,
  m3: M3,
  m4: M4,
  m5: M5,
  m6: M6,
  m7: M7,
  m8: M8,
  m9: M9,
  m10: M10,
  m11: M11,
  m12: M12,
  m13: M13,
  m14: M14,
  m15: M15,
  m16: M16,
  m17: M17,
  m18: M18,
  m19: M19,
  m20: M20
): Middleware<
  RequiredContextOf<M1> &
    Satisfy<RequiredContextOf<M2>, M1C> &
    Satisfy<RequiredContextOf<M3>, M2C> &
    Satisfy<RequiredContextOf<M4>, M3C> &
    Satisfy<RequiredContextOf<M5>, M4C> &
    Satisfy<RequiredContextOf<M6>, M5C> &
    Satisfy<RequiredContextOf<M7>, M6C> &
    Satisfy<RequiredContextOf<M8>, M7C> &
    Satisfy<RequiredContextOf<M9>, M8C> &
    Satisfy<RequiredContextOf<M10>, M9C> &
    Satisfy<RequiredContextOf<M11>, M10C> &
    Satisfy<RequiredContextOf<M12>, M11C> &
    Satisfy<RequiredContextOf<M13>, M12C> &
    Satisfy<RequiredContextOf<M14>, M13C> &
    Satisfy<RequiredContextOf<M15>, M14C> &
    Satisfy<RequiredContextOf<M16>, M15C> &
    Satisfy<RequiredContextOf<M17>, M16C> &
    Satisfy<RequiredContextOf<M18>, M17C> &
    Satisfy<RequiredContextOf<M19>, M18C> &
    Satisfy<RequiredContextOf<M20>, M19C>,
  M20C,
  EnvOf<M1> &
    EnvOf<M2> &
    EnvOf<M3> &
    EnvOf<M4> &
    EnvOf<M5> &
    EnvOf<M6> &
    EnvOf<M7> &
    EnvOf<M8> &
    EnvOf<M9> &
    EnvOf<M10> &
    EnvOf<M11> &
    EnvOf<M12> &
    EnvOf<M13> &
    EnvOf<M14> &
    EnvOf<M15> &
    EnvOf<M16> &
    EnvOf<M17> &
    EnvOf<M18> &
    EnvOf<M19> &
    EnvOf<M20>
>

export { composeMiddleware }
